### ISSUE TITLE
No English version support

### ISSUE THREAD

**Issue by HukuToc2288** [mihannnik/Black-List-in-Dialogs#1]
English version of VK uses names transliteration, so "Семён Литвинов" shows as "Semyon Litvinov" and thus cannot be filtered
![image](https://user-images.githubusercontent.com/24959862/151358765-6f667659-eebf-4c77-8874-27a53735b92a.png)

**Comment by mihannnik** [comment]
In last commit i added ability to create your own ignore list
![image](https://user-images.githubusercontent.com/48869235/151374323-27c13bfc-ec21-41be-b31b-0fc3ef3d403b.png)
